package parser

import (
	"fmt"
	"sort"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/xinchentechnote/fin-protoc/internal/model"
)

// cKeywords are reserved words that cannot be used as plain identifiers in C;
// when a DSL field name lowercases into one of them it is prefixed with '_'.
var cKeywords = map[string]struct{}{
	"auto": {}, "break": {}, "case": {}, "char": {}, "const": {}, "continue": {},
	"default": {}, "do": {}, "double": {}, "else": {}, "enum": {}, "extern": {},
	"float": {}, "for": {}, "goto": {}, "if": {}, "inline": {}, "int": {},
	"long": {}, "register": {}, "restrict": {}, "return": {}, "short": {},
	"signed": {}, "sizeof": {}, "static": {}, "struct": {}, "switch": {},
	"typedef": {}, "union": {}, "unsigned": {}, "void": {}, "volatile": {},
	"while": {}, "_bool": {}, "_complex": {}, "_imaginary": {},
}

// cBasicTypes maps normalized DSL scalar types to C types.
var cBasicTypes = map[string]string{
	"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t", "u64": "uint64_t",
	"i8": "int8_t", "i16": "int16_t", "i32": "int32_t", "i64": "int64_t",
	"f32": "float", "f64": "double", "char": "uint8_t",
}

// cPrefixBytes maps length-prefix types to their byte width.
var cPrefixBytes = map[string]int{"u8": 1, "u16": 2, "u32": 4, "u64": 8}

// CGenerator a C11 code generator. It emits one <snake>.h/.c pair per
// packet, an umbrella root.h and a tests.c with a round-trip test per
// packet, targeting the fin-proto-runtime-bin-c library. Wire semantics
// match the other generators: same runtime helper set, same checksum
// services, same length-prefix / padding rules.
type CGenerator struct {
	binModel *model.BinaryModel
}

// NewCGenerator new
func NewCGenerator(binModel *model.BinaryModel) *CGenerator {
	return &CGenerator{binModel: binModel}
}

// GetConfig get Configuration
func (g CGenerator) GetConfig() *model.Configuration {
	return g.binModel.Config
}

// Generate C code: declaration order keeps the output deterministic.
func (g CGenerator) Generate(binModel *model.BinaryModel) (map[string][]byte, error) {
	output := make(map[string][]byte)
	for _, pkt := range binModel.Packets {
		snake := strcase.ToSnake(pkt.Name)
		output[snake+".h"] = []byte(g.generatePacketHeader(pkt))
		output[snake+".c"] = []byte(g.generatePacketSource(pkt))
	}
	output["root.h"] = []byte(g.generateRootHeader())
	output["tests.c"] = []byte(g.generateTests())
	return output, nil
}

// prefix is the C symbol namespace: the root packet's snake_case name.
func (g CGenerator) prefix() string {
	if g.binModel.RootPacket != nil {
		return strcase.ToSnake(g.binModel.RootPacket.Name) + "_"
	}
	return ""
}

func cSnake(name string) string {
	s := strcase.ToSnake(name)
	if _, kw := cKeywords[s]; kw {
		return "_" + s
	}
	return s
}

func cUpperSnake(name string) string {
	return strings.ToUpper(strcase.ToSnake(name))
}

// cTypeName is the C type of a packet struct.
func (g CGenerator) cTypeName(pkt *model.Packet) string {
	return g.prefix() + strcase.ToSnake(pkt.Name)
}

func (g CGenerator) orderedPackets() []*model.Packet {
	return g.binModel.Packets
}

// referencedPackets returns the deduplicated, sorted packet names a packet's
// header must include (object refs + match pair values, not inner objects).
func referencedPackets(pkt *model.Packet) []string {
	refs := make(map[string]struct{})
	for _, f := range pkt.Fields {
		if mf, ok := f.Attr.(*model.MatchFieldAttribute); ok {
			for _, pair := range mf.MatchPairs {
				refs[pair.Value] = struct{}{}
			}
		} else if of, ok := f.Attr.(*model.ObjectFieldAttribute); ok && !of.IsIner {
			refs[of.PacketName] = struct{}{}
		}
	}
	names := make([]string, 0, len(refs))
	for name := range refs {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func (g CGenerator) usesChecksum(pkt *model.Packet) bool {
	for _, f := range pkt.Fields {
		if _, ok := f.Attr.(*model.CheckSumFieldAttribute); ok {
			return true
		}
	}
	return false
}

func (g CGenerator) generatePacketHeader(pkt *model.Packet) string {
	var b strings.Builder
	t := g.cTypeName(pkt)
	guard := "FC_" + cUpperSnake(pkt.Name) + "_H"
	b.WriteString("/* Code generated by fin-protoc. DO NOT EDIT. */\n")
	b.WriteString(fmt.Sprintf("#ifndef %s\n#define %s\n\n", guard, guard))
	b.WriteString("#include \"binary_codec.h\"\n")
	if g.usesChecksum(pkt) {
		b.WriteString("#include \"check_sum.h\"\n")
	}
	for _, ref := range referencedPackets(pkt) {
		b.WriteString(fmt.Sprintf("#include \"%s.h\"\n", strcase.ToSnake(ref)))
	}
	b.WriteString("\n")
	// inner object structs first, then the match enums, then the struct
	for _, f := range pkt.Fields {
		if of, ok := f.Attr.(*model.ObjectFieldAttribute); ok && of.IsIner {
			b.WriteString(g.generatePacketHeader(of.RefPacket))
			b.WriteString("\n")
		}
	}
	b.WriteString(g.generateMatchKindCode(pkt))
	// struct
	b.WriteString(fmt.Sprintf("typedef struct %s {\n", t))
	if len(pkt.Fields) == 0 {
		b.WriteString("    uint8_t _empty;\n")
	}
	for _, f := range pkt.Fields {
		if f.IsRepeat {
			b.WriteString(g.fieldDecl(g.cFieldTypeName(pkt, f), cSnake(f.Name)) + "\n")
			continue
		}
		switch f.Attr.(type) {
		case *model.MatchFieldAttribute:
			kindType := g.matchKindType(pkt, f)
			b.WriteString(fmt.Sprintf("    %s %s_tag;\n", kindType, cSnake(f.Name)))
			b.WriteString(fmt.Sprintf("    union {\n"))
			mf := f.Attr.(*model.MatchFieldAttribute)
			seen := map[string]struct{}{}
			for _, pair := range mf.MatchPairs {
				if _, dup := seen[pair.Value]; dup {
					continue
				}
				seen[pair.Value] = struct{}{}
				if sub, ok := g.binModel.PacketsMap[pair.Value]; ok {
					b.WriteString(fmt.Sprintf("        %s %s;\n", g.cTypeName(sub), cSnake(pair.Value)))
				} else {
					b.WriteString(fmt.Sprintf("        %s %s;\n", g.prefix()+strcase.ToSnake(pair.Value), cSnake(pair.Value)))
				}
			}
			b.WriteString("    } " + cSnake(f.Name) + ";\n")
		default:
			b.WriteString(fmt.Sprintf("    %s %s;\n", g.cFieldTypeName(pkt, f), cSnake(f.Name)))
		}
	}
	b.WriteString(fmt.Sprintf("} %s;\n\n", t))
	b.WriteString(fmt.Sprintf("bool %s_encode(const %s *self, fc_buffer *buf);\n", t, t))
	b.WriteString(fmt.Sprintf("bool %s_decode(fc_reader *r, %s *out);\n", t, t))
	b.WriteString(fmt.Sprintf("bool %s_eql(const %s *a, const %s *b);\n", t, t, t))
	b.WriteString(fmt.Sprintf("void %s_free(%s *self);\n\n", t, t))
	b.WriteString(fmt.Sprintf("#endif /* %s */\n", guard))
	return b.String()
}

// fieldDecl renders a repeat field as an element pointer plus a count.
func (g CGenerator) fieldDecl(elemType, name string) string {
	return fmt.Sprintf("    %s *%s;\n    uint32_t %s_count;", elemType, name, name)
}

// cFieldTypeName resolves the C type for a (non-match) field.
func (g CGenerator) cFieldTypeName(pkt *model.Packet, f *model.Field) string {
	switch c := f.Attr.(type) {
	case *model.FixedStringFieldAttribute, *model.DynamicStringFieldAttribute:
		return "fc_string"
	case *model.ObjectFieldAttribute:
		if c.RefPacket != nil {
			return g.cTypeName(c.RefPacket)
		}
		return g.prefix() + strcase.ToSnake(c.PacketName)
	default:
		if t, ok := cBasicTypes[f.GetType()]; ok {
			return t
		}
		return f.GetType()
	}
}

func (g CGenerator) matchKindType(pkt *model.Packet, f *model.Field) string {
	return strcase.ToSnake(pkt.Name) + "_" + cSnake(f.Name) + "_kind"
}

func (g CGenerator) matchKindConstant(pkt *model.Packet, f *model.Field, value string) string {
	return cUpperSnake(pkt.Name) + "_" + cUpperSnake(f.Name) + "_" + cUpperSnake(value)
}

func (g CGenerator) matchNoneConstant(pkt *model.Packet, f *model.Field) string {
	return cUpperSnake(pkt.Name) + "_" + cUpperSnake(f.Name) + "_NONE"
}

// generateMatchKindCode emits the body-kind enum for match fields.
func (g CGenerator) generateMatchKindCode(pkt *model.Packet) string {
	var b strings.Builder
	for _, f := range pkt.Fields {
		mf, ok := f.Attr.(*model.MatchFieldAttribute)
		if !ok {
			continue
		}
		b.WriteString(fmt.Sprintf("typedef enum {\n"))
		b.WriteString(fmt.Sprintf("    %s = 0,\n", g.matchNoneConstant(pkt, f)))
		seen := map[string]struct{}{}
		for _, pair := range mf.MatchPairs {
			if _, dup := seen[pair.Value]; dup {
				continue
			}
			seen[pair.Value] = struct{}{}
			b.WriteString(fmt.Sprintf("    %s,\n", g.matchKindConstant(pkt, f, pair.Value)))
		}
		b.WriteString(fmt.Sprintf("} %s;\n\n", g.matchKindType(pkt, f)))
	}
	return b.String()
}

func (g CGenerator) generateRootHeader() string {
	var b strings.Builder
	b.WriteString("/* Code generated by fin-protoc. DO NOT EDIT. */\n")
	b.WriteString("#ifndef FC_ROOT_H\n#define FC_ROOT_H\n\n")
	packets := g.orderedPackets()
	names := make([]string, 0, len(packets))
	for _, pkt := range packets {
		names = append(names, strcase.ToSnake(pkt.Name))
	}
	sort.Strings(names)
	for _, name := range names {
		b.WriteString(fmt.Sprintf("#include \"%s.h\"\n", name))
	}
	b.WriteString("\n#endif /* FC_ROOT_H */\n")
	return b.String()
}

func (g CGenerator) generatePacketSource(pkt *model.Packet) string {
	var b strings.Builder
	b.WriteString("/* Code generated by fin-protoc. DO NOT EDIT. */\n")
	b.WriteString(fmt.Sprintf("#include \"%s.h\"\n", strcase.ToSnake(pkt.Name)))
	b.WriteString("#include <stdlib.h>\n")
	b.WriteString("#include <string.h>\n\n")
	// inner (inline) object function bodies come first, mirroring the header
	// layout where their types precede the parent struct
	for _, f := range pkt.Fields {
		if of, ok := f.Attr.(*model.ObjectFieldAttribute); ok && of.IsIner {
			b.WriteString(g.generatePacketFunctions(of.RefPacket))
			b.WriteString("\n")
		}
	}
	b.WriteString(g.generatePacketFunctions(pkt))
	return b.String()
}

func (g CGenerator) generatePacketFunctions(pkt *model.Packet) string {
	var b strings.Builder
	b.WriteString(g.generateEncode(pkt))
	b.WriteString("\n")
	b.WriteString(g.generateDecode(pkt))
	b.WriteString("\n")
	b.WriteString(g.generateEql(pkt))
	b.WriteString("\n")
	b.WriteString(g.generateFree(pkt))
	return b.String()
}

func (g CGenerator) generateEncode(pkt *model.Packet) string {
	var b strings.Builder
	t := g.cTypeName(pkt)
	b.WriteString(fmt.Sprintf("bool %s_encode(const %s *self, fc_buffer *buf) {\n", t, t))
	if len(pkt.Fields) == 0 {
		b.WriteString("    (void)self;\n    (void)buf;\n    return true;\n}\n")
		return b.String()
	}
	usesSelf := false
	for _, f := range pkt.Fields {
		code := g.encodeField(pkt, f)
		if strings.Contains(code, "self->") {
			usesSelf = true
		}
		b.WriteString(indentLines(code, 1))
	}
	if !usesSelf {
		b.WriteString("    (void)self;\n")
	}
	b.WriteString("    return true;\n}\n")
	return b.String()
}

func (g CGenerator) encodeField(pkt *model.Packet, f *model.Field) string {
	name := cSnake(f.Name)
	if _, ok := f.Attr.(*model.LengthFieldAttribute); ok {
		var b strings.Builder
		b.WriteString(fmt.Sprintf("const size_t %s_pos = buf->len;\n", name))
		b.WriteString(fmt.Sprintf("if (!fc_buffer_put_%s(buf, 0)) return false;", cPutType(f.GetType())))
		return b.String()
	}
	if csf, ok := f.Attr.(*model.CheckSumFieldAttribute); ok {
		algo := strings.Trim(csf.CheckSumType, "\"")
		if fn, ok := g.checksumCall(algo, f.GetType()); ok {
			ctype := g.cFieldTypeName(pkt, f)
			return fmt.Sprintf("const %s checksum_val = %s(buf->data, buf->len);\nif (!fc_buffer_put_%s(buf, checksum_val)) return false;",
				ctype, fn, cPutType(f.GetType()))
		}
		return fmt.Sprintf("/* checksum %s not applied to field type %s; kept as-is */\nif (!fc_buffer_put_%s(buf, self->%s)) return false;",
			algo, f.GetType(), cPutType(f.GetType()), name)
	}
	padChar := g.cPadChar(f)
	padLeft := g.cPadLeft(f)
	if f.IsRepeat {
		var b strings.Builder
		b.WriteString(fmt.Sprintf("if (!fc_put_count(buf, %d, self->%s_count)) return false;\n", g.arrayPrefixBytes(), name))
		switch c := f.Attr.(type) {
		case *model.FixedStringFieldAttribute:
			putFn := "fc_put_char_array"
			padArgs := ""
			if !g.paddingIsDefault(f) {
				putFn = "fc_put_char_array_pad"
				padArgs = fmt.Sprintf(", %s, %d", padChar, boolToInt(padLeft))
			}
			b.WriteString(fmt.Sprintf("for (uint32_t i = 0; i < self->%s_count; i++) {\n", name))
			b.WriteString(fmt.Sprintf("    if (!%s(buf, self->%s[i].data, self->%s[i].len, %d%s)) return false;\n",
				putFn, name, name, c.Length, padArgs))
			b.WriteString("}")
		case *model.DynamicStringFieldAttribute:
			b.WriteString(fmt.Sprintf("for (uint32_t i = 0; i < self->%s_count; i++) {\n", name))
			b.WriteString(fmt.Sprintf("    if (!fc_put_string(buf, %d, self->%s[i].data, self->%s[i].len)) return false;\n",
				g.stringPrefixBytes(), name, name))
			b.WriteString("}")
		case *model.ObjectFieldAttribute:
			b.WriteString(fmt.Sprintf("for (uint32_t i = 0; i < self->%s_count; i++) {\n", name))
			b.WriteString(fmt.Sprintf("    if (!%s_encode(&self->%s[i], buf)) return false;\n", g.objectTypeName(pkt, f), name))
			b.WriteString("}")
		default:
			put := cPutType(f.GetType())
			if f.GetType() == "char" {
				put = "u8"
			}
			b.WriteString(fmt.Sprintf("for (uint32_t i = 0; i < self->%s_count; i++) {\n", name))
			b.WriteString(fmt.Sprintf("    if (!fc_buffer_put_%s(buf, self->%s[i])) return false;\n", put, name))
			b.WriteString("}")
		}
		return b.String()
	}
	switch c := f.Attr.(type) {
	case *model.FixedStringFieldAttribute:
		fn := "fc_put_char_array"
		args := ""
		if !g.paddingIsDefault(f) {
			fn = "fc_put_char_array_pad"
			args = fmt.Sprintf(", %s, %d", padChar, boolToInt(padLeft))
		}
		return fmt.Sprintf("if (!%s(buf, self->%s.data, self->%s.len, %d%s)) return false;",
			fn, name, name, c.Length, args)
	case *model.DynamicStringFieldAttribute:
		return fmt.Sprintf("if (!fc_put_string(buf, %d, self->%s.data, self->%s.len)) return false;",
			g.stringPrefixBytes(), name, name)
	case *model.MatchFieldAttribute:
		var b strings.Builder
		hasLength := false
		if _, ok := f.LenAttr.(*model.LengthFieldAttribute); ok {
			hasLength = true
			b.WriteString(fmt.Sprintf("const size_t %s_start = buf->len;\n", name))
		}
		b.WriteString(fmt.Sprintf("switch (self->%s_tag) {\n", name))
		b.WriteString(fmt.Sprintf("    case %s:\n        break;\n", g.matchNoneConstant(pkt, f)))
		seen := map[string]struct{}{}
		for _, pair := range c.MatchPairs {
			if _, dup := seen[pair.Value]; dup {
				continue
			}
			seen[pair.Value] = struct{}{}
			b.WriteString(fmt.Sprintf("    case %s:\n", g.matchKindConstant(pkt, f, pair.Value)))
			b.WriteString(fmt.Sprintf("        if (!%s_encode(&self->%s.%s, buf)) return false;\n        break;\n",
				g.matchValueTypeName(pair.Value), name, cSnake(pair.Value)))
		}
		b.WriteString("}")
		if hasLength {
			b.WriteString("\n")
			b.WriteString(fmt.Sprintf("if (!fc_buffer_patch_%s(buf, %s_pos, (uint32_t)(buf->len - %s_start))) return false;",
				cPutType(pkt.LengthField.GetType()), strcase.ToSnake(pkt.LengthField.Name), name))
		}
		return b.String()
	case *model.ObjectFieldAttribute:
		if _, ok := f.LenAttr.(*model.LengthFieldAttribute); ok {
			return fmt.Sprintf("const size_t %s_start = buf->len;\n"+
				"if (!%s_encode(&self->%s, buf)) return false;\n"+
				"if (!fc_buffer_patch_%s(buf, %s_pos, (uint32_t)(buf->len - %s_start))) return false;",
				name, g.objectTypeName(pkt, f), name,
				cPutType(pkt.LengthField.GetType()), strcase.ToSnake(pkt.LengthField.Name), name)
		}
		return fmt.Sprintf("if (!%s_encode(&self->%s, buf)) return false;", g.objectTypeName(pkt, f), name)
	default:
		put := cPutType(f.GetType())
		return fmt.Sprintf("if (!fc_buffer_put_%s(buf, self->%s)) return false;", put, name)
	}
}

// checksumCall maps (algorithm, field type) to the runtime function; only the
// natural pairing is accepted, mirroring the generated Rust exact-variant match.
func (g CGenerator) checksumCall(algo, fieldType string) (string, bool) {
	switch algo {
	case "SSE_BIN":
		if ct, ok := cBasicTypes[fieldType]; ok && strings.HasPrefix(ct, "uint") {
			return "fc_sse_bin", true
		}
	case "SZSE_BIN":
		if fieldType == "i32" {
			return "fc_szse_bin", true
		}
	case "CRC16":
		if fieldType == "u16" {
			return "fc_crc16", true
		}
	case "CRC32":
		if fieldType == "u32" {
			return "fc_crc32", true
		}
	}
	return "", false
}

func (g CGenerator) generateDecode(pkt *model.Packet) string {
	var b strings.Builder
	t := g.cTypeName(pkt)
	b.WriteString(fmt.Sprintf("bool %s_decode(fc_reader *r, %s *out) {\n", t, t))
	b.WriteString("    memset(out, 0, sizeof(*out));\n")
	if len(pkt.Fields) == 0 {
		b.WriteString("    (void)r;\n    return true;\n}\n")
		return b.String()
	}
	for _, f := range pkt.Fields {
		b.WriteString(indentLines(g.decodeField(pkt, f), 1))
	}
	b.WriteString("    return true;\n}\n")
	return b.String()
}

func (g CGenerator) decodeField(pkt *model.Packet, f *model.Field) string {
	name := cSnake(f.Name)
	if f.IsRepeat {
		var b strings.Builder
		b.WriteString(fmt.Sprintf("uint64_t %s_n = 0;\n", name))
		b.WriteString(fmt.Sprintf("if (!fc_get_count(r, %d, &%s_n)) return false;\n", g.arrayPrefixBytes(), name))
		b.WriteString(fmt.Sprintf("out->%s_count = (uint32_t)%s_n;\n", name, name))
		b.WriteString(fmt.Sprintf("if (%s_n == 0) {\n    out->%s = NULL;\n} else {\n", name, name))
		switch f.Attr.(type) {
		case *model.FixedStringFieldAttribute, *model.DynamicStringFieldAttribute:
			b.WriteString(fmt.Sprintf("    out->%s = (fc_string *)calloc((size_t)%s_n, sizeof(fc_string));\n", name, name))
		case *model.ObjectFieldAttribute:
			b.WriteString(fmt.Sprintf("    out->%s = (%s *)calloc((size_t)%s_n, sizeof(%s));\n",
				name, g.objectTypeName(pkt, f), name, g.objectTypeName(pkt, f)))
		default:
			b.WriteString(fmt.Sprintf("    out->%s = (%s *)calloc((size_t)%s_n, sizeof(%s));\n",
				name, g.cFieldTypeName(pkt, f), name, g.cFieldTypeName(pkt, f)))
		}
		b.WriteString(fmt.Sprintf("    if (out->%s == NULL) return false;\n", name))
		b.WriteString(fmt.Sprintf("    for (uint64_t i = 0; i < %s_n; i++) {\n", name))
		switch c := f.Attr.(type) {
		case *model.FixedStringFieldAttribute:
			trimFn := "fc_get_char_array"
			if !g.paddingIsDefault(f) {
				trimFn = "fc_get_char_array_trim"
			}
			padArgs := ""
			if trimFn == "fc_get_char_array_trim" {
				padArgs = fmt.Sprintf(", %s, %d", g.cPadChar(f), boolToInt(g.cPadLeft(f)))
			}
			b.WriteString(fmt.Sprintf("        if (!%s(r, %d%s, &out->%s[i])) return false;\n",
				trimFn, c.Length, padArgs, name))
		case *model.DynamicStringFieldAttribute:
			b.WriteString(fmt.Sprintf("        if (!fc_get_string(r, %d, &out->%s[i])) return false;\n",
				g.stringPrefixBytes(), name))
		case *model.ObjectFieldAttribute:
			b.WriteString(fmt.Sprintf("        if (!%s_decode(r, &out->%s[i])) return false;\n",
				g.objectTypeName(pkt, f), name))
		default:
			get := cPutType(f.GetType())
			if f.GetType() == "char" {
				get = "u8"
			}
			b.WriteString(fmt.Sprintf("        if (!fc_reader_get_%s(r, &out->%s[i])) return false;\n", get, name))
		}
		b.WriteString("    }\n}")
		return b.String()
	}
	switch c := f.Attr.(type) {
	case *model.FixedStringFieldAttribute:
		fn := "fc_get_char_array"
		args := ""
		if !g.paddingIsDefault(f) {
			fn = "fc_get_char_array_trim"
			args = fmt.Sprintf(", %s, %d", g.cPadChar(f), boolToInt(g.cPadLeft(f)))
		}
		return fmt.Sprintf("if (!%s(r, %d%s, &out->%s)) return false;", fn, c.Length, args, name)
	case *model.DynamicStringFieldAttribute:
		return fmt.Sprintf("if (!fc_get_string(r, %d, &out->%s)) return false;", g.stringPrefixBytes(), name)
	case *model.MatchFieldAttribute:
		var b strings.Builder
		matchKey := cSnake(c.MatchKeyField.Name)
		if g.HasQuotes(c.MatchPairs[0].Key) {
			// string keys: group by target value, first-seen order
			var values []string
			keysByValue := make(map[string][]string)
			for _, pair := range c.MatchPairs {
				if _, exists := keysByValue[pair.Value]; !exists {
					values = append(values, pair.Value)
				}
				keysByValue[pair.Value] = append(keysByValue[pair.Value], pair.Key)
			}
			for i, value := range values {
				conds := make([]string, 0, len(keysByValue[value]))
				for _, key := range keysByValue[value] {
					conds = append(conds, fmt.Sprintf("fc_streq_lit(out->%s, %s)", matchKey, key))
				}
				keyword := "if"
				if i > 0 {
					keyword = "else if"
				}
				b.WriteString(fmt.Sprintf("%s (%s) {\n", keyword, strings.Join(conds, " || ")))
				b.WriteString(fmt.Sprintf("    out->%s_tag = %s;\n", name, g.matchKindConstant(pkt, f, value)))
				b.WriteString(fmt.Sprintf("    if (!%s_decode(r, &out->%s.%s)) return false;\n",
					g.matchValueTypeName(value), name, cSnake(value)))
				b.WriteString("} ")
			}
			b.WriteString("else {\n    return false; /* unknown message type */\n}")
			return b.String()
		}
		b.WriteString(fmt.Sprintf("switch (out->%s) {\n", matchKey))
		seen := map[string]struct{}{}
		for _, pair := range c.MatchPairs {
			if _, dup := seen[pair.Key]; dup {
				continue
			}
			seen[pair.Key] = struct{}{}
			b.WriteString(fmt.Sprintf("    case %s:\n", pair.Key))
			b.WriteString(fmt.Sprintf("        out->%s_tag = %s;\n", name, g.matchKindConstant(pkt, f, pair.Value)))
			b.WriteString(fmt.Sprintf("        if (!%s_decode(r, &out->%s.%s)) return false;\n        break;\n",
				g.matchValueTypeName(pair.Value), name, cSnake(pair.Value)))
		}
		b.WriteString("    default:\n        return false; /* unknown message type */\n}")
		return b.String()
	case *model.ObjectFieldAttribute:
		return fmt.Sprintf("if (!%s_decode(r, &out->%s)) return false;", g.objectTypeName(pkt, f), name)
	default:
		return fmt.Sprintf("if (!fc_reader_get_%s(r, &out->%s)) return false;", cPutType(f.GetType()), name)
	}
}

func (g CGenerator) generateEql(pkt *model.Packet) string {
	var b strings.Builder
	t := g.cTypeName(pkt)
	b.WriteString(fmt.Sprintf("bool %s_eql(const %s *a, const %s *b) {\n", t, t, t))
	if len(pkt.Fields) == 0 {
		b.WriteString("    (void)a;\n    (void)b;\n    return true;\n}\n")
		return b.String()
	}
	for _, f := range pkt.Fields {
		b.WriteString(indentLines(g.eqlField(pkt, f), 1))
	}
	b.WriteString("    return true;\n}\n")
	return b.String()
}

func (g CGenerator) eqlField(pkt *model.Packet, f *model.Field) string {
	name := cSnake(f.Name)
	if f.IsRepeat {
		var b strings.Builder
		b.WriteString(fmt.Sprintf("if (a->%s_count != b->%s_count) return false;\n", name, name))
		switch f.Attr.(type) {
		case *model.FixedStringFieldAttribute, *model.DynamicStringFieldAttribute:
			b.WriteString(fmt.Sprintf("for (uint32_t i = 0; i < a->%s_count; i++) {\n", name))
			b.WriteString("    if (!fc_string_eql(a->" + name + "[i], b->" + name + "[i])) return false;\n}")
		case *model.ObjectFieldAttribute:
			b.WriteString(fmt.Sprintf("for (uint32_t i = 0; i < a->%s_count; i++) {\n", name))
			b.WriteString(fmt.Sprintf("    if (!%s_eql(&a->%s[i], &b->%s[i])) return false;\n}",
				g.objectTypeName(pkt, f), name, name))
		default:
			b.WriteString(fmt.Sprintf("for (uint32_t i = 0; i < a->%s_count; i++) {\n", name))
			b.WriteString("    if (a->" + name + "[i] != b->" + name + "[i]) return false;\n}")
		}
		return b.String()
	}
	switch f.Attr.(type) {
	case *model.FixedStringFieldAttribute, *model.DynamicStringFieldAttribute:
		return fmt.Sprintf("if (!fc_string_eql(a->%s, b->%s)) return false;", name, name)
	case *model.MatchFieldAttribute:
		var b strings.Builder
		b.WriteString(fmt.Sprintf("if (a->%s_tag != b->%s_tag) return false;\n", name, name))
		b.WriteString(fmt.Sprintf("switch (a->%s_tag) {\n", name))
		b.WriteString(fmt.Sprintf("    case %s:\n        break;\n", g.matchNoneConstant(pkt, f)))
		mf := f.Attr.(*model.MatchFieldAttribute)
		seen := map[string]struct{}{}
		for _, pair := range mf.MatchPairs {
			if _, dup := seen[pair.Value]; dup {
				continue
			}
			seen[pair.Value] = struct{}{}
			b.WriteString(fmt.Sprintf("    case %s:\n", g.matchKindConstant(pkt, f, pair.Value)))
			b.WriteString(fmt.Sprintf("        if (!%s_eql(&a->%s.%s, &b->%s.%s)) return false;\n        break;\n",
				g.matchValueTypeName(pair.Value), name, cSnake(pair.Value), name, cSnake(pair.Value)))
		}
		b.WriteString("}")
		return b.String()
	case *model.ObjectFieldAttribute:
		return fmt.Sprintf("if (!%s_eql(&a->%s, &b->%s)) return false;", g.objectTypeName(pkt, f), name, name)
	default:
		return fmt.Sprintf("if (a->%s != b->%s) return false;", name, name)
	}
}

func (g CGenerator) generateFree(pkt *model.Packet) string {
	var b strings.Builder
	t := g.cTypeName(pkt)
	b.WriteString(fmt.Sprintf("void %s_free(%s *self) {\n", t, t))
	emitted := false
	for _, f := range pkt.Fields {
		if !f.IsRepeat {
			continue
		}
		emitted = true
		name := cSnake(f.Name)
		switch f.Attr.(type) {
		case *model.ObjectFieldAttribute:
			b.WriteString(fmt.Sprintf("    for (uint32_t i = 0; i < self->%s_count; i++) {\n", name))
			b.WriteString(fmt.Sprintf("        %s_free(&self->%s[i]);\n    }\n", g.objectTypeName(pkt, f), name))
		}
		b.WriteString(fmt.Sprintf("    free(self->%s);\n    self->%s = NULL;\n    self->%s_count = 0;\n", name, name, name))
	}
	for _, f := range pkt.Fields {
		mf, ok := f.Attr.(*model.MatchFieldAttribute)
		if !ok {
			continue
		}
		emitted = true
		name := cSnake(f.Name)
		b.WriteString(fmt.Sprintf("    switch (self->%s_tag) {\n", name))
		seen := map[string]struct{}{}
		for _, pair := range mf.MatchPairs {
			if _, dup := seen[pair.Value]; dup {
				continue
			}
			seen[pair.Value] = struct{}{}
			b.WriteString(fmt.Sprintf("    case %s:\n", g.matchKindConstant(pkt, f, pair.Value)))
			b.WriteString(fmt.Sprintf("        %s_free(&self->%s.%s);\n        break;\n",
				g.matchValueTypeName(pair.Value), name, cSnake(pair.Value)))
		}
		b.WriteString(fmt.Sprintf("    case %s:\n        break;\n    }\n", g.matchNoneConstant(pkt, f)))
		b.WriteString(fmt.Sprintf("    self->%s_tag = %s;\n", name, g.matchNoneConstant(pkt, f)))
	}
	if !emitted {
		b.WriteString("    (void)self;\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

// generateTests emits a single tests.c with one round-trip test per packet
// and a main() runner (no external test framework required).
func (g CGenerator) generateTests() string {
	var b strings.Builder
	b.WriteString("/* Code generated by fin-protoc. DO NOT EDIT. */\n")
	b.WriteString("#include \"root.h\"\n")
	b.WriteString("#include <stdio.h>\n")
	b.WriteString("#include <stdlib.h>\n")
	b.WriteString("#include <string.h>\n\n")
	b.WriteString("#define CHECK(x) \\\n")
	b.WriteString("    do { \\\n")
	b.WriteString("        if (!(x)) { \\\n")
	b.WriteString("            fprintf(stderr, \"CHECK failed: %s (%s:%d)\\n\", #x, __FILE__, __LINE__); \\\n")
	b.WriteString("            exit(1); \\\n")
	b.WriteString("        } \\\n")
	b.WriteString("    } while (0)\n\n")

	endian := 0
	if g.GetConfig().LittleEndian {
		endian = 1
	}
	for _, pkt := range g.orderedPackets() {
		t := g.cTypeName(pkt)
		b.WriteString(fmt.Sprintf("static void test_%s_codec(void) {\n", strcase.ToSnake(pkt.Name)))
		b.WriteString(fmt.Sprintf("    %s msg;\n", t))
		b.WriteString("    memset(&msg, 0, sizeof(msg));\n")
		for _, line := range g.testAssignments(pkt, "msg") {
			b.WriteString("    " + line + "\n")
		}
		b.WriteString("\n    fc_buffer buf;\n")
		b.WriteString(fmt.Sprintf("    fc_buffer_init(&buf, %d);\n", endian))
		b.WriteString(fmt.Sprintf("    CHECK(%s_encode(&msg, &buf));\n", t))
		b.WriteString("\n    fc_reader reader;\n")
		b.WriteString(fmt.Sprintf("    fc_reader_init(&reader, buf.data, buf.len, %d);\n", endian))
		b.WriteString(fmt.Sprintf("    %s decoded;\n", t))
		b.WriteString(fmt.Sprintf("    CHECK(%s_decode(&reader, &decoded));\n", t))
		for _, f := range pkt.Fields {
			switch f.Attr.(type) {
			case *model.LengthFieldAttribute, *model.CheckSumFieldAttribute:
				b.WriteString(fmt.Sprintf("    msg.%s = decoded.%s;\n", cSnake(f.Name), cSnake(f.Name)))
			}
		}
		b.WriteString(fmt.Sprintf("    CHECK(%s_eql(&msg, &decoded));\n", t))
		b.WriteString(fmt.Sprintf("    %s_free(&decoded);\n", t))
		b.WriteString("    fc_buffer_free(&buf);\n")
		b.WriteString("}\n\n")
	}

	b.WriteString("int main(void) {\n")
	for _, pkt := range g.orderedPackets() {
		b.WriteString(fmt.Sprintf("    test_%s_codec();\n", strcase.ToSnake(pkt.Name)))
	}
	b.WriteString("    printf(\"all tests passed\\n\");\n")
	b.WriteString("    return 0;\n")
	b.WriteString("}\n")
	return b.String()
}

// testAssignments builds the C assignment statements constructing a sample
// instance of the packet at the given base path (e.g. "msg").
func (g CGenerator) testAssignments(pkt *model.Packet, path string) []string {
	var lines []string
	for _, f := range pkt.Fields {
		name := cSnake(f.Name)
		if mf, ok := f.Attr.(*model.MatchFieldAttribute); ok {
			if len(mf.MatchPairs) == 0 {
				continue
			}
			key := mf.MatchPairs[0].Key
			if g.HasQuotes(key) {
				lines = append(lines, fmt.Sprintf("%s.%s = FC_STR(%s);", path, cSnake(mf.MatchKeyField.Name), key))
			} else {
				lines = append(lines, fmt.Sprintf("%s.%s = %s;", path, cSnake(mf.MatchKeyField.Name), key))
			}
			first := mf.MatchPairs[0].Value
			lines = append(lines, fmt.Sprintf("%s.%s_tag = %s;", path, name, g.matchKindConstant(pkt, f, first)))
			if sub, ok := g.binModel.PacketsMap[first]; ok {
				lines = append(lines, g.testAssignments(sub, fmt.Sprintf("%s.%s.%s", path, name, cSnake(first)))...)
			}
			continue
		}
		if pkt.MatchFields[f.Name] != nil {
			continue // match key fields are set together with the match field
		}
		switch c := f.Attr.(type) {
		case *model.LengthFieldAttribute, *model.CheckSumFieldAttribute:
			// zero-initialized; recomputed or patched on the wire
		case *model.ObjectFieldAttribute:
			if f.IsRepeat {
				// empty object lists keep the zero-initialized NULL/0 pair
				continue
			}
			if c.RefPacket != nil {
				lines = append(lines, g.testAssignments(c.RefPacket, path+"."+name)...)
			}
		default:
			if f.IsRepeat {
				lines = append(lines, g.testRepeatAssignments(f, path, name)...)
				continue
			}
			if fs, ok := f.Attr.(*model.FixedStringFieldAttribute); ok {
				lines = append(lines, fmt.Sprintf("%s.%s = FC_STR(\"%s\");", path, name, strings.Repeat("a", fs.Length)))
				continue
			}
			lines = append(lines, fmt.Sprintf("%s.%s = %s;", path, name, g.cTestSingleValue(f)))
		}
	}
	return lines
}

func (g CGenerator) testRepeatAssignments(f *model.Field, path, name string) []string {
	var elems []string
	count := 0
	if fs, ok := f.Attr.(*model.FixedStringFieldAttribute); ok {
		count = fs.Length
		for i := 0; i < fs.Length; i++ {
			elems = append(elems, `FC_STR("a")`)
		}
	} else if _, ok := f.Attr.(*model.ObjectFieldAttribute); ok {
		// empty object lists keep the zero-initialized NULL/0 pair
		return nil
	} else {
		elems = strings.Split(g.cTestListValue(f), ", ")
		count = len(elems)
	}
	var lines []string
	elemType := "fc_string"
	if _, ok := f.Attr.(*model.DynamicStringFieldAttribute); !ok {
		if _, isFixed := f.Attr.(*model.FixedStringFieldAttribute); !isFixed {
			if t, ok := cBasicTypes[f.GetType()]; ok {
				elemType = t
			}
		}
	}
	lines = append(lines, fmt.Sprintf("%s %s_vals[] = { %s };", elemType, name, strings.Join(elems, ", ")))
	lines = append(lines, fmt.Sprintf("%s.%s = %s_vals;", path, name, name))
	lines = append(lines, fmt.Sprintf("%s.%s_count = %d;", path, name, count))
	return lines
}

func (g CGenerator) cTestSingleValue(f *model.Field) string {
	switch f.Attr.(type) {
	case *model.LengthFieldAttribute:
		return "0"
	}
	if v, ok := g.cPrimitiveSingleValues()[f.GetType()]; ok {
		return v
	}
	return "0"
}

func (g CGenerator) cTestListValue(f *model.Field) string {
	if v, ok := g.cPrimitiveListValues()[f.GetType()]; ok {
		return v
	}
	return "0, 0"
}

func (g CGenerator) cPrimitiveSingleValues() map[string]string {
	return map[string]string{
		"string": `FC_STR("example")`,
		"char":   `'a'`,
		"u8":     "42",
		"u16":    "1234",
		"u32":    "123456",
		"u64":    "123456789",
		"i8":     "-42",
		"i16":    "-1234",
		"i32":    "-123456",
		"i64":    "-123456789",
		"f32":    "12345.678f",
		"f64":    "12345.678",
	}
}

func (g CGenerator) cPrimitiveListValues() map[string]string {
	return map[string]string{
		"string": `FC_STR("example"), FC_STR("test")`,
		"char":   `'a', 'b'`,
		"u8":     "42, 12",
		"u16":    "1234, 4321",
		"u32":    "123456, 654321",
		"u64":    "123456789, 987654321",
		"i8":     "-42, -12",
		"i16":    "-1234, -4321",
		"i32":    "-123456, -654321",
		"i64":    "-123456789, -987654321",
		"f32":    "12345.678f, 87654.321f",
		"f64":    "12345.678, 87654.321",
	}
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

func (g CGenerator) objectTypeName(pkt *model.Packet, f *model.Field) string {
	return g.cFieldTypeName(pkt, f)
}

func (g CGenerator) matchValueTypeName(value string) string {
	if sub, ok := g.binModel.PacketsMap[value]; ok {
		return g.cTypeName(sub)
	}
	return g.prefix() + strcase.ToSnake(value)
}

func (g CGenerator) arrayPrefixBytes() int {
	if n, ok := cPrefixBytes[g.GetConfig().ListLenPrefixLenType]; ok {
		return n
	}
	return 2
}

func (g CGenerator) stringPrefixBytes() int {
	if n, ok := cPrefixBytes[g.GetConfig().StringLenPrefixLenType]; ok {
		return n
	}
	return 2
}

// cPutType maps a DSL type to the suffix of the fc_buffer_put_/fc_reader_get_
// runtime functions (identical spelling for all C integer/float types).
func cPutType(t string) string {
	if t == "char" {
		return "u8"
	}
	return t
}

// GetPadding returns the effective padding (field attribute wins over the
// global configuration), normalized as a copy.
func (g CGenerator) GetPadding(f *model.Field) *model.Padding {
	padding := g.GetConfig().Padding
	if fs, ok := f.Attr.(*model.FixedStringFieldAttribute); ok {
		if fs.Padding != nil {
			padding = fs.Padding
		}
	}
	if padding == nil {
		return nil
	}
	padChar := padding.PadChar
	switch padChar {
	case "'\x00'", "'\\x00'", "'\\u0000'", "'\\0'":
		padChar = "'\\0'"
	}
	return &model.Padding{PadChar: padChar, PadLeft: padding.PadLeft}
}

func (g CGenerator) paddingIsDefault(f *model.Field) bool {
	padding := g.GetPadding(f)
	return padding == nil || padding.IsDefault()
}

// cPadChar renders the pad character as a C char literal.
func (g CGenerator) cPadChar(f *model.Field) string {
	padding := g.GetPadding(f)
	if padding == nil {
		return "' '"
	}
	inner := padding.PadChar
	if len(inner) >= 2 && inner[0] == '\'' && inner[len(inner)-1] == '\'' {
		inner = inner[1 : len(inner)-1]
	}
	if inner == "\\x00" || inner == "\x00" {
		inner = "\\0"
	}
	return "'" + inner + "'"
}

func (g CGenerator) cPadLeft(f *model.Field) bool {
	padding := g.GetPadding(f)
	return padding != nil && padding.PadLeft
}

func (g CGenerator) padCallArgs(f *model.Field, padChar string, padLeft bool) string {
	if g.paddingIsDefault(f) {
		return ""
	}
	return fmt.Sprintf(", %s, %d", padChar, boolToInt(padLeft))
}

// HasQuotes is string literal
func (g CGenerator) HasQuotes(s string) bool {
	if len(s) < 2 {
		return false
	}
	first, last := s[0], s[len(s)-1]
	return first == '"' && last == '"'
}

func boolToInt(v bool) int {
	if v {
		return 1
	}
	return 0
}

func indentLines(s string, levels int) string {
	indent := strings.Repeat("    ", levels)
	return indent + strings.ReplaceAll(s, "\n", "\n"+indent) + "\n"
}
