package parser

import (
	"fmt"
	"sort"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/xinchentechnote/fin-protoc/internal/model"
)

// zigKeywords are reserved words that cannot be used as plain identifiers in
// Zig; when a DSL field name lowercases into one of them it is emitted as
// @"name".
var zigKeywords = map[string]struct{}{
	"abstract": {}, "addrspace": {}, "align": {}, "allowzero": {}, "and": {},
	"anyframe": {}, "anytype": {}, "asm": {}, "await": {}, "break": {},
	"callconv": {}, "catch": {}, "comptime": {}, "const": {}, "continue": {},
	"defer": {}, "else": {}, "enum": {}, "errdefer": {}, "error": {},
	"export": {}, "extern": {}, "false": {}, "fn": {}, "for": {}, "if": {},
	"inline": {}, "noalias": {}, "noinline": {}, "nosuspend": {}, "null": {},
	"opaque": {}, "or": {}, "orelse": {}, "packed": {}, "pub": {},
	"resume": {}, "return": {}, "linksection": {}, "struct": {}, "suspend": {},
	"switch": {}, "test": {}, "threadlocal": {}, "true": {}, "type": {},
	"undefined": {}, "union": {}, "unreachable": {}, "usingnamespace": {}, "var": {},
	"volatile": {}, "while": {},
}

// ZigGenerator a zig code generator. It emits one <snake>.zig file per
// packet plus a root.zig re-exporting every public type, targeting the
// fin-proto-runtime-bin-zig `binary_codec` module. The wire semantics match
// the Rust generator: same runtime helper set, same checksum services and
// the same length-prefix / padding rules.
type ZigGenerator struct {
	binModel *model.BinaryModel
}

// NewZigGenerator new
func NewZigGenerator(binModel *model.BinaryModel) *ZigGenerator {
	return &ZigGenerator{
		binModel: binModel,
	}
}

// GetConfig get Configuration
func (g ZigGenerator) GetConfig() *model.Configuration {
	return g.binModel.Config
}

// Generate zig code: one file per packet (declaration order, so the output
// is deterministic) plus root.zig.
func (g ZigGenerator) Generate(binModel *model.BinaryModel) (map[string][]byte, error) {
	output := make(map[string][]byte)
	for _, pkt := range binModel.Packets {
		code := g.generateZigFileForPacket(pkt)
		output[strcase.ToSnake(pkt.Name)+".zig"] = []byte(code)
	}
	output["root.zig"] = []byte(g.generateRootCode())
	return output, nil
}

func (g ZigGenerator) generateZigFileForPacket(pkt *model.Packet) string {
	var b strings.Builder

	b.WriteString("// Code generated by fin-protoc. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Decoded strings borrow from the input buffer and stay valid only while the\n")
	b.WriteString("// input bytes do; deinit frees only the outer repeat slices allocated by\n")
	b.WriteString("// decode. Requires the `binary_codec` module (fin-proto-runtime-bin-zig).\n\n")
	b.WriteString("const std = @import(\"std\");\n")
	b.WriteString("const codec = @import(\"binary_codec\");\n\n")
	b.WriteString(g.generateImportCode(pkt))
	b.WriteString(g.generateMatchFieldEnumCode(pkt))
	b.WriteString(g.generateStructCode(pkt))

	return b.String()
}

// generateRootCode re-exports every packet module and public type so
// consumers only need `@import("<module>")`.
func (g ZigGenerator) generateRootCode() string {
	var b strings.Builder
	b.WriteString("// Code generated by fin-protoc. DO NOT EDIT.\n\n")

	packets := make([]*model.Packet, 0, len(g.binModel.Packets))
	packets = append(packets, g.binModel.Packets...)
	sort.Slice(packets, func(i, j int) bool {
		return strcase.ToSnake(packets[i].Name) < strcase.ToSnake(packets[j].Name)
	})

	for _, pkt := range packets {
		snake := strcase.ToSnake(pkt.Name)
		b.WriteString(fmt.Sprintf("pub const %s = @import(\"%s.zig\");\n", snake, snake))
	}
	b.WriteString("\n")
	for _, pkt := range packets {
		snake := strcase.ToSnake(pkt.Name)
		camel := strcase.ToCamel(pkt.Name)
		b.WriteString(fmt.Sprintf("pub const %s = %s.%s;\n", camel, snake, camel))
		for _, f := range pkt.Fields {
			if _, ok := f.Attr.(*model.MatchFieldAttribute); ok {
				enumName := camel + f.Name + "Enum"
				b.WriteString(fmt.Sprintf("pub const %s = %s.%s;\n", enumName, snake, enumName))
			}
		}
	}
	// reference every module so Zig's lazy analysis collects the per-packet
	// test blocks when this root is compiled as a test target
	b.WriteString("\ntest {\n")
	for _, pkt := range packets {
		b.WriteString(fmt.Sprintf("    _ = %s;\n", strcase.ToSnake(pkt.Name)))
	}
	b.WriteString("}\n")
	return b.String()
}

// generateImportCode emits direct type imports for every packet referenced
// by an object field or a match pair.
func (g ZigGenerator) generateImportCode(msg *model.Packet) string {
	var b strings.Builder
	imports := make(map[string]struct{})
	for _, f := range msg.Fields {
		if mf, ok := f.Attr.(*model.MatchFieldAttribute); ok {
			for _, pair := range mf.MatchPairs {
				imports[pair.Value] = struct{}{}
			}
		} else if c, ok := f.Attr.(*model.ObjectFieldAttribute); ok && !c.IsIner {
			imports[c.PacketName] = struct{}{}
		}
	}
	names := make([]string, 0, len(imports))
	for name := range imports {
		if name == msg.Name {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		camel := strcase.ToCamel(name)
		b.WriteString(fmt.Sprintf("const %s = @import(\"%s.zig\").%s;\n", camel, strcase.ToSnake(name), camel))
	}
	if len(names) > 0 {
		b.WriteString("\n")
	}
	return b.String()
}

// generateMatchFieldEnumCode generates a tagged union per match field, with
// value semantics eql/deinit helpers.
func (g ZigGenerator) generateMatchFieldEnumCode(packet *model.Packet) string {
	var b strings.Builder
	for _, f := range packet.Fields {
		if _, ok := f.Attr.(*model.MatchFieldAttribute); !ok {
			continue
		}
		mf := f.Attr.(*model.MatchFieldAttribute)
		enumName := strcase.ToCamel(packet.Name) + f.Name + "Enum"
		b.WriteString(fmt.Sprintf("pub const %s = union(enum) {\n", enumName))
		matchValues := make(map[string]struct{})
		for _, pair := range mf.MatchPairs {
			if _, exists := matchValues[pair.Value]; exists {
				continue // Skip if already added
			}
			matchValues[pair.Value] = struct{}{}
			b.WriteString(AddIndent4ln(fmt.Sprintf("%s: %s,", strcase.ToSnake(pair.Value), strcase.ToCamel(pair.Value))))
		}
		b.WriteString("\n")
		b.WriteString(AddIndent4ln(fmt.Sprintf("pub fn eql(self: %s, other: %s) bool {", enumName, enumName)))
		b.WriteString(AddIndent4ln(AddIndent4("if (std.meta.activeTag(self) != std.meta.activeTag(other)) return false;")))
		b.WriteString(AddIndent4ln(AddIndent4("return switch (self) {")))
		b.WriteString(AddIndent4ln(AddIndent4(AddIndent4("inline else => |payload, tag| payload.eql(@field(other, @tagName(tag))),"))))
		b.WriteString(AddIndent4ln(AddIndent4("};")))
		b.WriteString(AddIndent4ln("}"))
		b.WriteString("\n")
		b.WriteString(AddIndent4ln(fmt.Sprintf("pub fn deinit(self: %s, allocator: std.mem.Allocator) void {", enumName)))
		b.WriteString(AddIndent4ln(AddIndent4("switch (self) {")))
		b.WriteString(AddIndent4ln(AddIndent4(AddIndent4("inline else => |payload| payload.deinit(allocator),"))))
		b.WriteString(AddIndent4ln(AddIndent4("}")))
		b.WriteString(AddIndent4ln("}"))
		b.WriteString("};\n\n")
	}
	return b.String()
}

func (g ZigGenerator) generateStructCode(pkt *model.Packet) string {
	var b strings.Builder
	// inline (nested) object structs come first, mirroring the Rust generator
	for _, f := range pkt.Fields {
		if of, ok := f.Attr.(*model.ObjectFieldAttribute); ok && of.IsIner {
			b.WriteString(g.generateStructCode(of.RefPacket))
			b.WriteString("\n")
		}
	}
	structName := strcase.ToCamel(pkt.Name)
	b.WriteString(fmt.Sprintf("pub const %s = struct {\n", structName))
	for _, f := range pkt.Fields {
		fieldType := g.GetFieldType(structName, f)
		if f.IsRepeat {
			fieldType = "[]const " + fieldType
		}
		b.WriteString(AddIndent4ln(fmt.Sprintf("%s: %s,", g.GetFieldName(f), fieldType)))
	}
	if len(pkt.Fields) > 0 {
		b.WriteString("\n")
	}

	// encode()
	b.WriteString(AddIndent4ln(fmt.Sprintf("pub fn encode(self: *const %s, buf: *codec.Buffer) !void {", structName)))
	encodeSelfUsed := false
	if len(pkt.Fields) > 0 {
		for _, f := range pkt.Fields {
			code := g.EncodeField(pkt, f)
			if strings.Contains(code, "self.") {
				encodeSelfUsed = true
			}
			b.WriteString(AddIndent4ln(AddIndent4(code)))
		}
	}
	if !encodeSelfUsed {
		b.WriteString(AddIndent4ln(AddIndent4("_ = self;")))
	}
	if len(pkt.Fields) == 0 {
		b.WriteString(AddIndent4ln(AddIndent4("_ = buf;")))
	}
	b.WriteString(AddIndent4ln("}"))
	b.WriteString("\n")

	// decode()
	b.WriteString(AddIndent4ln(fmt.Sprintf("pub fn decode(allocator: std.mem.Allocator, r: *codec.Reader) codec.DecodeError!%s {", structName)))
	if len(pkt.Fields) == 0 {
		b.WriteString(AddIndent4ln(AddIndent4("_ = allocator;")))
		b.WriteString(AddIndent4ln(AddIndent4("_ = r;")))
		b.WriteString(AddIndent4ln(AddIndent4(fmt.Sprintf("return %s{};", structName))))
	} else {
		if !g.decodeNeedsAllocator(pkt) {
			b.WriteString(AddIndent4ln(AddIndent4("_ = allocator;")))
		}
		for _, f := range pkt.Fields {
			b.WriteString(AddIndent4ln(AddIndent4(g.DecodeField(structName, f))))
		}
		b.WriteString(AddIndent4ln(AddIndent4("return .{")))
		for _, f := range pkt.Fields {
			b.WriteString(AddIndent4ln(AddIndent4(AddIndent4("." + g.GetFieldName(f) + " = " + g.GetFieldName(f) + ","))))
		}
		b.WriteString(AddIndent4ln(AddIndent4("};")))
	}
	b.WriteString(AddIndent4ln("}"))
	b.WriteString("\n")

	// deinit() frees exactly what decode() allocated
	b.WriteString(AddIndent4ln(fmt.Sprintf("pub fn deinit(self: %s, allocator: std.mem.Allocator) void {", structName)))
	freedSomething := false
	for _, f := range pkt.Fields {
		if !f.IsRepeat {
			continue
		}
		freedSomething = true
		switch f.Attr.(type) {
		case *model.ObjectFieldAttribute:
			b.WriteString(AddIndent4ln(AddIndent4(fmt.Sprintf("for (self.%s) |item| item.deinit(allocator);", g.GetFieldName(f)))))
		}
		b.WriteString(AddIndent4ln(AddIndent4(fmt.Sprintf("allocator.free(self.%s);", g.GetFieldName(f)))))
	}
	if !freedSomething {
		b.WriteString(AddIndent4ln(AddIndent4("_ = self;")))
		b.WriteString(AddIndent4ln(AddIndent4("_ = allocator;")))
	}
	b.WriteString(AddIndent4ln("}"))
	b.WriteString("\n")

	// eql() is a deep, generated equality (the wire-safe equivalent of the
	// derived PartialEq the other generators emit)
	b.WriteString(AddIndent4ln(fmt.Sprintf("pub fn eql(self: %s, other: %s) bool {", structName, structName)))
	if len(pkt.Fields) == 0 {
		b.WriteString(AddIndent4ln(AddIndent4("_ = self;")))
		b.WriteString(AddIndent4ln(AddIndent4("_ = other;")))
		b.WriteString(AddIndent4ln(AddIndent4("return true;")))
	} else {
		for _, f := range pkt.Fields {
			b.WriteString(AddIndent4ln(AddIndent4(g.EqlField(f))))
		}
		b.WriteString(AddIndent4ln(AddIndent4("return true;")))
	}
	b.WriteString(AddIndent4ln("}"))
	b.WriteString("};\n\n")

	b.WriteString(g.generateUnitTestCode(pkt))
	return b.String()
}

// decodeNeedsAllocator reports whether any decode line requires the
// allocator: repeat fields allocate their outer slice and object/match
// fields recurse into another decode.
func (g ZigGenerator) decodeNeedsAllocator(pkt *model.Packet) bool {
	for _, f := range pkt.Fields {
		if f.IsRepeat {
			return true
		}
		switch f.Attr.(type) {
		case *model.ObjectFieldAttribute, *model.MatchFieldAttribute:
			return true
		}
	}
	return false
}

// GetPadding returns the effective padding for the field (field-level
// attribute wins over the global configuration), normalized for Zig string
// literals. Returns a copy so the shared model is never rewritten.
func (g ZigGenerator) GetPadding(f *model.Field) *model.Padding {
	padding := g.GetConfig().Padding
	if fs, ok := f.Attr.(*model.FixedStringFieldAttribute); ok {
		if fs.Padding != nil {
			padding = fs.Padding
		}
	}
	if padding == nil {
		return nil
	}
	padChar := padding.PadChar
	switch padChar {
	case "'\x00'", "'\\x00'", "'\\u0000'":
		padChar = "'\\x00'"
	}
	return &model.Padding{PadChar: padChar, PadLeft: padding.PadLeft}
}

// getZigPadChar renders the pad character as a Zig char literal.
func (g ZigGenerator) getZigPadChar(f *model.Field) string {
	padding := g.GetPadding(f)
	if padding == nil {
		return "' '"
	}
	inner := padding.PadChar
	if len(inner) >= 2 && inner[0] == '\'' && inner[len(inner)-1] == '\'' {
		inner = inner[1 : len(inner)-1]
	}
	if inner == "\\0" || inner == "\x00" {
		inner = "\\x00"
	}
	return "'" + inner + "'"
}

// GetFieldType convert field type for zig
func (g ZigGenerator) GetFieldType(parentName string, f *model.Field) string {
	switch c := f.Attr.(type) {
	case *model.FixedStringFieldAttribute, *model.DynamicStringFieldAttribute:
		return "[]const u8"
	case *model.MatchFieldAttribute:
		return parentName + f.Name + "Enum"
	case *model.ObjectFieldAttribute:
		if c.RefPacket != nil {
			return strcase.ToCamel(c.RefPacket.Name)
		}
		return strcase.ToCamel(c.PacketName)
	default:
		// Zig has no `char` primitive; single-char fields are u8 on the wire
		if f.GetType() == "char" {
			return "u8"
		}
		return f.GetType()
	}
}

// GetFieldName returns the field name in snake_case format, escaped with
// @"..." when it collides with a Zig keyword.
func (g ZigGenerator) GetFieldName(f *model.Field) string {
	name := strcase.ToSnake(f.Name)
	if _, kw := zigKeywords[name]; kw {
		return "@\"" + name + "\""
	}
	return name
}

// EncodeField encoding field
func (g ZigGenerator) EncodeField(p *model.Packet, f *model.Field) string {
	if _, ok := f.Attr.(*model.LengthFieldAttribute); ok {
		// auto-calculated length field: reserve the space here, the target
		// field patches it once its encoded size is known
		var b strings.Builder
		b.WriteString(fmt.Sprintf("const %s_pos = buf.len;\n", strcase.ToSnake(f.Name)))
		b.WriteString(fmt.Sprintf("try buf.put(%s, 0);", f.GetType()))
		return b.String()
	}

	if csf, ok := f.Attr.(*model.CheckSumFieldAttribute); ok {
		algo := strings.Trim(csf.CheckSumType, "\"")
		return fmt.Sprintf("try buf.put(%s, codec.computeChecksum(%s, %q, buf.written(), self.%s));",
			f.GetType(), f.GetType(), algo, g.GetFieldName(f))
	}

	name := g.GetFieldName(f)
	padding := g.GetPadding(f)
	paddingIsDefault := padding == nil || padding.IsDefault()
	padChar := g.getZigPadChar(f)
	listLenType := g.GetConfig().ListLenPrefixLenType
	if f.IsRepeat {
		switch c := f.Attr.(type) {
		case *model.FixedStringFieldAttribute:
			if !paddingIsDefault {
				return fmt.Sprintf("try codec.putFixedStringListWithPad(%s, buf, self.%s, %d, %s, %t);",
					listLenType, name, c.Length, padChar, padding.PadLeft)
			}
			return fmt.Sprintf("try codec.putFixedStringList(%s, buf, self.%s, %d);", listLenType, name, c.Length)
		case *model.DynamicStringFieldAttribute:
			return fmt.Sprintf("try codec.putStringList(%s,%s, buf, self.%s);",
				listLenType, g.GetConfig().StringLenPrefixLenType, name)
		case *model.ObjectFieldAttribute:
			return fmt.Sprintf("try codec.putObjectList(%s, %s, buf, self.%s);",
				g.GetFieldType("", f), listLenType, name)
		}
		if f.GetType() == "char" {
			return fmt.Sprintf("try codec.putList(u8, %s, buf, self.%s);", listLenType, name)
		}
		return fmt.Sprintf("try codec.putList(%s, %s, buf, self.%s);", f.GetType(), listLenType, name)
	}

	if fs, ok := f.Attr.(*model.FixedStringFieldAttribute); ok {
		if !paddingIsDefault {
			return fmt.Sprintf("try codec.putCharArrayWithPad(buf, self.%s, %d, %s, %t);",
				name, fs.Length, padChar, padding.PadLeft)
		}
		return fmt.Sprintf("try codec.putCharArray(buf, self.%s, %d);", name, fs.Length)
	}

	switch c := f.Attr.(type) {
	case *model.DynamicStringFieldAttribute:
		return fmt.Sprintf("try codec.putString(%s, buf, self.%s);", g.GetConfig().StringLenPrefixLenType, name)

	case *model.MatchFieldAttribute:
		var b strings.Builder
		hasLength := false
		if _, ok := f.LenAttr.(*model.LengthFieldAttribute); ok {
			hasLength = true
			b.WriteString(fmt.Sprintf("const %s_start = buf.len;\n", strcase.ToSnake(f.Name)))
		}
		b.WriteString(g.encodeMatchField(strcase.ToCamel(p.Name), f, c))
		if hasLength {
			b.WriteString("\n")
			b.WriteString(fmt.Sprintf("try buf.patch(%s, %s_pos, @intCast(buf.len - %s_start));",
				p.LengthField.GetType(), strcase.ToSnake(p.LengthField.Name), strcase.ToSnake(f.Name)))
		}
		return b.String()
	case *model.ObjectFieldAttribute:
		if _, ok := f.LenAttr.(*model.LengthFieldAttribute); ok {
			fieldSnake := strcase.ToSnake(f.Name)
			return fmt.Sprintf("const %s_start = buf.len;\ntry self.%s.encode(buf);\ntry buf.patch(%s, %s_pos, @intCast(buf.len - %s_start));",
				fieldSnake, name, p.LengthField.GetType(), strcase.ToSnake(p.LengthField.Name), fieldSnake)
		}
		return fmt.Sprintf("try self.%s.encode(buf);", name)
	default:
		switch f.GetType() {
		case "char":
			return fmt.Sprintf("try buf.put(u8, self.%s);", name)
		case "u8", "i8", "u16", "u32", "u64", "i16", "i32", "i64", "f32", "f64":
			return fmt.Sprintf("try buf.put(%s, self.%s);", f.GetType(), name)
		default:
			return fmt.Sprintf("// unknown type for encode: %s", f.GetType())
		}
	}
}

// encodeMatchField encodes the tagged union via an inline else switch; the
// union tags are generated from the match pairs so a single inline else arm
// dispatches to every variant's encode.
func (g ZigGenerator) encodeMatchField(parentName string, f *model.Field, mfa *model.MatchFieldAttribute) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("switch (self.%s) {\n", g.GetFieldName(f)))
	if len(mfa.MatchPairs) > 0 {
		b.WriteString(AddIndent4ln("inline else => |msg| try msg.encode(buf),"))
	}
	b.WriteString("}")
	return b.String()
}

// DecodeField decoding field
func (g ZigGenerator) DecodeField(parentName string, f *model.Field) string {
	name := g.GetFieldName(f)
	padding := g.GetPadding(f)
	paddingIsDefault := padding == nil || padding.IsDefault()
	padChar := g.getZigPadChar(f)
	listLenType := g.GetConfig().ListLenPrefixLenType
	if f.IsRepeat {
		switch c := f.Attr.(type) {
		case *model.FixedStringFieldAttribute:
			if !paddingIsDefault {
				return fmt.Sprintf("const %s = try codec.getFixedStringListTrimPad(%s, allocator, r, %d, %s, %t);",
					name, listLenType, c.Length, padChar, padding.PadLeft)
			}
			return fmt.Sprintf("const %s = try codec.getFixedStringList(%s, allocator, r, %d);", name, listLenType, c.Length)
		case *model.DynamicStringFieldAttribute:
			return fmt.Sprintf("const %s = try codec.getStringList(%s,%s, allocator, r);",
				name, listLenType, g.GetConfig().StringLenPrefixLenType)
		case *model.ObjectFieldAttribute:
			return fmt.Sprintf("const %s = try codec.getObjectList(%s, %s, allocator, r);",
				name, g.GetFieldType(parentName, f), listLenType)
		}
		if f.GetType() == "char" {
			return fmt.Sprintf("const %s = try codec.getList(u8, %s, allocator, r);", name, listLenType)
		}
		return fmt.Sprintf("const %s = try codec.getList(%s, %s, allocator, r);", name, f.GetType(), listLenType)
	}

	switch c := f.Attr.(type) {
	case *model.FixedStringFieldAttribute:
		if !paddingIsDefault {
			return fmt.Sprintf("const %s = try codec.getCharArrayTrimPad(r, %d, %s, %t);",
				name, c.Length, padChar, padding.PadLeft)
		}
		return fmt.Sprintf("const %s = try codec.getCharArray(r, %d);", name, c.Length)
	case *model.DynamicStringFieldAttribute:
		return fmt.Sprintf("const %s = try codec.getString(%s, r);", name, g.GetConfig().StringLenPrefixLenType)
	case *model.MatchFieldAttribute:
		return g.decodeMatchField(parentName, f, c)
	case *model.ObjectFieldAttribute:
		typeName := g.GetFieldType(parentName, f)
		return fmt.Sprintf("const %s = try %s.decode(allocator, r);", name, typeName)
	}

	if _, ok := f.Attr.(*model.LengthFieldAttribute); ok {
		return fmt.Sprintf("const %s = try r.get(%s);", name, f.GetType())
	}
	if _, ok := f.Attr.(*model.CheckSumFieldAttribute); ok {
		return fmt.Sprintf("const %s = try r.get(%s);", name, f.GetType())
	}

	switch f.GetType() {
	case "char":
		return fmt.Sprintf("const %s = try r.get(u8);", name)
	case "u8", "i8", "u16", "u32", "u64", "i16", "i32", "i64", "f32", "f64":
		return fmt.Sprintf("const %s = try r.get(%s);", name, f.GetType())
	default:
		return fmt.Sprintf("// unknown type for decode: %s", f.GetType())
	}
}

// HasQuotes is string literal
func (g ZigGenerator) HasQuotes(s string) bool {
	if len(s) < 2 {
		return false
	}
	first, last := s[0], s[len(s)-1]
	return (first == '"' && last == '"')
}

// decodeMatchField decodes the tagged union: numeric keys become switch
// prongs, string keys an if/else chain over std.mem.eql.
func (g ZigGenerator) decodeMatchField(parentName string, f *model.Field, mfa *model.MatchFieldAttribute) string {
	var b strings.Builder
	fieldName := g.GetFieldName(f)
	enumName := parentName + f.Name + "Enum"
	matchKey := strcase.ToSnake(mfa.MatchKeyField.Name)
	if _, kw := zigKeywords[matchKey]; kw {
		matchKey = "@\"" + matchKey + "\""
	}

	if g.HasQuotes(mfa.MatchPairs[0].Key) {
		// group string keys by target value, first-seen order
		var values []string
		keysByValue := make(map[string][]string)
		for _, pair := range mfa.MatchPairs {
			if _, exists := keysByValue[pair.Value]; !exists {
				values = append(values, pair.Value)
			}
			keysByValue[pair.Value] = append(keysByValue[pair.Value], pair.Key)
		}
		b.WriteString(fmt.Sprintf("const %s: %s = ", fieldName, enumName))
		for i, value := range values {
			conds := make([]string, 0, len(keysByValue[value]))
			for _, key := range keysByValue[value] {
				conds = append(conds, fmt.Sprintf("std.mem.eql(u8, %s, %s)", matchKey, key))
			}
			keyword := "if"
			if i > 0 {
				keyword = "else if"
			}
			b.WriteString(fmt.Sprintf("%s (%s)\n", keyword, strings.Join(conds, " or ")))
			b.WriteString(AddIndent4ln(fmt.Sprintf(".{ .%s = try %s.decode(allocator, r) }", strcase.ToSnake(value), value)))
		}
		b.WriteString("else\n")
		b.WriteString(AddIndent4ln("return error.UnknownMessageType;"))
		return strings.TrimSuffix(b.String(), "\n")
	} else {
		b.WriteString(fmt.Sprintf("const %s: %s = switch (%s) {\n", fieldName, enumName, matchKey))
		pairs := make(map[string]struct{})
		for _, pair := range mfa.MatchPairs {
			if _, exists := pairs[pair.Key]; exists {
				continue
			}
			pairs[pair.Key] = struct{}{}
			b.WriteString(AddIndent4ln(fmt.Sprintf("%s => .{ .%s = try %s.decode(allocator, r) },",
				pair.Key, strcase.ToSnake(pair.Value), pair.Value)))
		}
		b.WriteString(AddIndent4ln("else => return error.UnknownMessageType,"))
		b.WriteString("};")
	}
	return b.String()
}

// EqlField generates one deep-equality check for a field.
func (g ZigGenerator) EqlField(f *model.Field) string {
	name := g.GetFieldName(f)
	if f.IsRepeat {
		switch f.Attr.(type) {
		case *model.ObjectFieldAttribute:
			return fmt.Sprintf("if (self.%s.len != other.%s.len) return false;\nfor (self.%s, other.%s) |a, b| {\n    if (!a.eql(b)) return false;\n}",
				name, name, name, name)
		case *model.FixedStringFieldAttribute, *model.DynamicStringFieldAttribute:
			return fmt.Sprintf("if (self.%s.len != other.%s.len) return false;\nfor (self.%s, other.%s) |a, b| {\n    if (!std.mem.eql(u8, a, b)) return false;\n}",
				name, name, name, name)
		default:
			return fmt.Sprintf("if (self.%s.len != other.%s.len) return false;\nfor (self.%s, other.%s) |a, b| {\n    if (a != b) return false;\n}",
				name, name, name, name)
		}
	}
	switch f.Attr.(type) {
	case *model.FixedStringFieldAttribute, *model.DynamicStringFieldAttribute:
		return fmt.Sprintf("if (!std.mem.eql(u8, self.%s, other.%s)) return false;", name, name)
	case *model.ObjectFieldAttribute, *model.MatchFieldAttribute:
		return fmt.Sprintf("if (!self.%s.eql(other.%s)) return false;", name, name)
	default:
		return fmt.Sprintf("if (self.%s != other.%s) return false;", name, name)
	}
}

func (g ZigGenerator) endianLiteral() string {
	if g.GetConfig().LittleEndian {
		return ".little"
	}
	return ".big"
}

func (g ZigGenerator) generateUnitTestCode(pkt *model.Packet) string {
	var b strings.Builder
	name := strcase.ToSnake(pkt.Name)
	structName := strcase.ToCamel(pkt.Name)
	endian := g.endianLiteral()

	hasPatchBack := false
	for _, f := range pkt.Fields {
		switch f.Attr.(type) {
		case *model.LengthFieldAttribute, *model.CheckSumFieldAttribute:
			hasPatchBack = true
		}
	}
	decl := "const"
	if hasPatchBack {
		decl = "var"
	}

	b.WriteString(fmt.Sprintf("test \"test_%s_codec\" {\n", name))
	b.WriteString(AddIndent4ln("var arena = std.heap.ArenaAllocator.init(std.testing.allocator);"))
	b.WriteString(AddIndent4ln("defer arena.deinit();"))
	b.WriteString(AddIndent4ln("const allocator = arena.allocator();"))
	b.WriteString("\n")

	// new instance
	fieldInits := make([]string, 0, len(pkt.Fields))
	for _, f := range pkt.Fields {
		if mf, ok := f.Attr.(*model.MatchFieldAttribute); ok {
			if len(mf.MatchPairs) > 0 {
				fieldInits = append(fieldInits, fmt.Sprintf(".%s = %s,", g.GetFieldName(mf.MatchKeyField), mf.MatchPairs[0].Key))
				fieldInits = append(fieldInits, fmt.Sprintf(".%s = %s,", g.GetFieldName(f), g.testValue(pkt.Name, f)))
			}
			continue
		}
		if pkt.MatchFields[f.Name] != nil {
			continue
		}
		fieldInits = append(fieldInits, fmt.Sprintf(".%s = %s,", g.GetFieldName(f), g.testValue(pkt.Name, f)))
	}
	if len(fieldInits) == 0 {
		b.WriteString(AddIndent4ln(fmt.Sprintf("%s msg = %s{};", decl, structName)))
	} else {
		b.WriteString(AddIndent4ln(fmt.Sprintf("%s msg = %s{", decl, structName)))
		for _, line := range fieldInits {
			b.WriteString(AddIndent4ln(AddIndent4(line)))
		}
		b.WriteString(AddIndent4ln("};"))
	}
	b.WriteString("\n")

	// encoding
	b.WriteString(AddIndent4ln(fmt.Sprintf("var buf = codec.Buffer.init(allocator, %s);", endian)))
	b.WriteString(AddIndent4ln("defer buf.deinit();"))
	b.WriteString(AddIndent4ln("try msg.encode(&buf);"))
	b.WriteString("\n")

	// decoding
	b.WriteString(AddIndent4ln(fmt.Sprintf("var reader = codec.Reader.init(buf.written(), %s);", endian)))
	b.WriteString(AddIndent4ln(fmt.Sprintf("const decoded = try %s.decode(allocator, &reader);", structName)))
	b.WriteString(AddIndent4ln("defer decoded.deinit(allocator);"))
	for _, f := range pkt.Fields {
		switch f.Attr.(type) {
		case *model.LengthFieldAttribute, *model.CheckSumFieldAttribute:
			b.WriteString(AddIndent4ln(fmt.Sprintf("msg.%s = decoded.%s;", g.GetFieldName(f), g.GetFieldName(f))))
		}
	}
	// assertion
	b.WriteString(AddIndent4ln("try std.testing.expect(msg.eql(decoded));"))
	b.WriteString("}\n")

	return b.String()
}

// testValue gen test value for different field types
func (g ZigGenerator) testValue(parentName string, f *model.Field) string {
	if f.IsRepeat {
		return g.testValueList(f)
	}
	return g.testValueSingle(parentName, f)
}

func (g ZigGenerator) testValueList(f *model.Field) string {
	if fs, ok := f.Attr.(*model.FixedStringFieldAttribute); ok {
		elements := make([]string, 0, fs.Length)
		for i := 0; i < fs.Length; i++ {
			elements = append(elements, `"a"`)
		}
		return fmt.Sprintf("&[_][]const u8{ %s }", strings.Join(elements, ", "))
	}
	if c, ok := f.Attr.(*model.ObjectFieldAttribute); ok {
		typeName := strcase.ToCamel(c.PacketName)
		if c.RefPacket != nil {
			typeName = strcase.ToCamel(c.RefPacket.Name)
		}
		return fmt.Sprintf("&[_]%s{}", typeName)
	}
	if val, ok := g.primitiveListValues()[f.GetType()]; ok {
		return val
	}
	return "&[_]u8{}"
}

func (g ZigGenerator) testValueSingle(parentName string, f *model.Field) string {
	switch c := f.Attr.(type) {
	case *model.LengthFieldAttribute:
		return "0"
	case *model.MatchFieldAttribute:
		return g.testMatchValue(parentName, f, c)
	case *model.FixedStringFieldAttribute:
		elements := make([]string, 0, c.Length)
		for i := 0; i < c.Length; i++ {
			elements = append(elements, "a")
		}
		return fmt.Sprintf("%q", strings.Join(elements, ""))
	case *model.ObjectFieldAttribute:
		// If it's a nested object, we need to create a default instance
		if c.RefPacket == nil {
			return ".{}"
		}
		var fieldValues []string
		for _, subField := range c.RefPacket.Fields {
			fieldValues = append(fieldValues, fmt.Sprintf(".%s = %s", g.GetFieldName(subField), g.testValue(c.RefPacket.Name, subField)))
		}
		if len(fieldValues) == 0 {
			return ".{}"
		}
		return fmt.Sprintf(".{ %s }", strings.Join(fieldValues, ", "))
	default:
		// handle primitive
		if val, ok := g.primitiveSingleValues()[f.GetType()]; ok {
			return val
		}
		return "undefined"
	}
}

func (g ZigGenerator) primitiveListValues() map[string]string {
	return map[string]string{
		"string": `&[_][]const u8{ "example", "test" }`,
		"char":   `&[_]u8{ 'a', 'b' }`,
		"u8":     "&[_]u8{ 42, 12 }",
		"u16":    "&[_]u16{ 1234, 4321 }",
		"u32":    "&[_]u32{ 123456, 654321 }",
		"u64":    "&[_]u64{ 123456789, 987654321 }",
		"i8":     "&[_]i8{ -42, -12 }",
		"i16":    "&[_]i16{ -1234, -4321 }",
		"i32":    "&[_]i32{ -123456, -654321 }",
		"i64":    "&[_]i64{ -123456789, -987654321 }",
		"f32":    "&[_]f32{ 12345.678, 87654.321 }",
		"f64":    "&[_]f64{ 12345.678, 87654.321 }",
	}
}

func (g ZigGenerator) primitiveSingleValues() map[string]string {
	return map[string]string{
		"string": `"example"`,
		"char":   `'a'`,
		"u8":     "42",
		"u16":    "1234",
		"u32":    "123456",
		"u64":    "123456789",
		"i8":     "-42",
		"i16":    "-1234",
		"i32":    "-123456",
		"i64":    "-123456789",
		"f32":    "12345.678",
		"f64":    "12345.678",
	}
}

func (g ZigGenerator) testMatchValue(parentName string, f *model.Field, mf *model.MatchFieldAttribute) string {
	if len(mf.MatchPairs) == 0 {
		return ".{}"
	}

	matchName := mf.MatchPairs[0].Value
	subPacket := g.binModel.PacketsMap[matchName]
	if subPacket == nil {
		return ".{}"
	}
	var innerFields []string
	for _, subField := range subPacket.Fields {
		innerFields = append(innerFields,
			fmt.Sprintf(".%s = %s", g.GetFieldName(subField), g.testValue(parentName, subField)))
	}
	if len(innerFields) == 0 {
		return fmt.Sprintf(".{ .%s = .{} }", strcase.ToSnake(matchName))
	}
	return fmt.Sprintf(".{ .%s = .{ %s } }",
		strcase.ToSnake(matchName),
		strings.Join(innerFields, ", "))
}
